### ISSUE TITLE
When using swarm1.0, cannot start container, memory.swappiness: invalid argument

### ISSUE THREAD

**Issue by fsfshijm** [docker/swarm#1411]
swarm1.0 + docker1.9 + docker-compose1.5

```
$> docker info
Containers: 7
Images: 17
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 EP003: 192.168.0.17:2375
  └ Containers: 5
  └ Reserved CPUs: 0 / 50
  └ Reserved Memory: 0 B / 131.9 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.1.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.1 (Maipo), storagedriver=devicemapper
 PEKdev233.dev.fwmrm.net: 192.168.0.233:2375
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-123.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.0 (Maipo), storagedriver=devicemapper
CPUs: 54
Total Memory: 148.2 GiB
Name: c34d6a96258c

$> docker-compose up -d
Starting manual_data_1
ERROR: Cannot start container e677d36e76dfe3486ee4fdd949cd6848d4f416917683384c86df4f7cf253217b: [8] System error: write /sys/fs/cgroup/memory/docker/e677d36e76dfe3486ee4fdd949cd6848d4f416917683384c86df4f7cf253217b/memory.swappiness: invalid argument

$> docker -v
Docker version 1.9.0, build 76d6bc9

$> docker-compose -v
docker-compose version: 1.5.0

$> docker images
REPOSITORY                             TAG                  IMAGE ID            CREATED             VIRTUAL SIZE
swarm                                  latest               6b40fe7724bd        9 days ago          15.6 MB

$> cat /proc/sys/vm/swappiness
10
```

**Comment by fsfshijm** [comment]
I can run 'docker-compose up -d' directly against the docker engines, (not swarm)  with no problem
My OS is RHEL7
Could I set swappiness on swarm?

**Comment by jimmyxian** [comment]
@fsfshijm Can you provide compose yml file?

**Comment by fsfshijm** [comment]
@jimmyxian

**Comment by fsfshijm** [comment]
@jimmyxian 
$>  cat docker-compose.yml
```
script:
  image: registry.docker.dev.fwmrm.net/mrm-be:redhat7-script
  links:
    - ads
    - hourly
    - oltp
  volumes_from:
    - hourly
  environment:
    - OLTPHOST=oltp
    - ADSHOST=ads
    - ADSLOGHOST=hourly
    - VOLUMEDIR=/work/local_data/script_volume
  command: /usr/sbin/sshd -D


hourly:
  image: registry.docker.dev.fwmrm.net/mrm-be:redhat5-ads-log
  links:
    - ads
    - oltp
  volumes_from:
    - ads
  ports:
    - "54702:44702"
  environment:
    - VOLUMEDIR=/work/local_data/hourly_volume
  command: /usr/sbin/sshd -D

ads:
  image: registry.docker.dev.fwmrm.net/mrm-be:redhat7-ads
  links:
    - oltp
    - data
  volumes:
    - /work
  volumes_from:
    - data
  ports:
    - "44701:44701"
  environment:
    - VOLUMEDIR=/work/local_data/ads_volume
  command: /usr/sbin/sshd -D

oltp:
  image: registry.docker.dev.fwmrm.net/mrm-be:redhat7-oltp
  links:
    - data
  volumes:
    - /home/jmshi/work/be-ci-build/build/..//data/ci:/work/ci
  volumes_from:
    - data
  ports:
    - "3311:3310"
  environment:
    - VOLUMEDIR=/work/local_data/oltp_volume
  command: /usr/sbin/sshd -D

data:
  image: registry.docker.dev.fwmrm.net/mrm-be:redhat7-local-data
  volumes:
    - /home/jmshi/work/be-ci-build/build/..//docker/dockerfiles/local_data/volume:/work/local_data/volume
  command: /usr/sbin/sshd -D
```
thanks!
