### ISSUE TITLE
Constraint:node and volumes dependency issue

### ISSUE THREAD

**Issue by bergtwvd** [docker/swarm#1439]
I have a container C that needs to run on a specific node with an associated data container D:

When using Docker-Compose in combination with Docker-swarm, I am not able to start the container.

Snippet of my compose file:

```
ge:
 volumes_from:
 - ge-settings
 environment:
 - alternate_lsd=/tmp/settings/alternate.lsd
 - "constraint:node==ip-172-31-9-126"
 image: myname/myimage
 container_name: ge
 ports:
 - "8765:8765"

ge-settings:
 image: myname/mydata
```

Container C will follow D w.r.t. location, which may not satisfy the constraint put on C.
I tried to add a node constraint on D, without effect.

How can this be done?

**Comment by nazar-pc** [comment]
I can't force it to use any constraints at all, for instance:
```
Containers: 10
Images: 24
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 5
 master: 192.168.99.101:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.12-boot2docker, operatingsystem=Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015, provider=virtualbox, storagedriver=aufs
 slave-1: 192.168.99.102:2376
  └ Containers: 4
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 512 MiB / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.12-boot2docker, operatingsystem=Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015, provider=virtualbox, storagedriver=aufs
 slave-2: 192.168.99.103:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.12-boot2docker, operatingsystem=Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015, provider=virtualbox, storagedriver=aufs
 slave-3: 192.168.99.104:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.12-boot2docker, operatingsystem=Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015, provider=virtualbox, storagedriver=aufs
 slave-4: 192.168.99.105:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 517.6 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.12-boot2docker, operatingsystem=Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 5
Total Memory: 2.527 GiB
Name: 20a86d99da81
```
```yml
# docker-compose.yml
...
mariadb:
  image: nazarpc/webserver:mariadb
  environment:
    - SERVICE_NAME=mariadb
    - constraint:node==slave-2
  volumes_from:
    - data
...
```

```
$ docker-compose --x-networking scale mariadb=2
Creating and starting 2 ... error

ERROR: for 2  unable to find a node that satisfies node==slave-2 
```

Similar results with `constraint:container!=*mariadb*` and any other constraints/affinities:(

Ubuntu 16.04 x64, Kernel 4.3.0, latest versions of Engine, Compose, Machine, Swarm
