### ISSUE TITLE
Incorrect driver name when creating an application on Swarm using Docker Compose 

### ISSUE THREAD

**Issue by arun-gupta** [docker/swarm#1461]
Creating application environment in Swarm cluster using the following Compose file:

```
mycouchbase:
  container_name: "db"
  image: couchbase/server
  ports:
    - 8091:8091
    - 8092:8092 
    - 8093:8093 
    - 11210:11210
mywildfly:
  image: arungupta/wildfly-admin
  environment:
    - COUCHBASE_URI=db
  ports:
    - 8080:8080
    - 9990:9990
```

Command is: `docker-compose --x-networking up -d`

Output shown is:

```
docker-compose --x-networking up -d
Creating network "wildflycouchbasejavaee7" with driver "None"
Pulling mywildfly (arungupta/wildfly-admin:latest)...
swarm-master: Pulling arungupta/wildfly-admin:latest...
swarm-node-01: Pulling arungupta/wildfly-admin:latest...
swarm-node-02: Pulling arungupta/wildfly-admin:latest...
```

`docker network ls` shows:

```
docker network ls
NETWORK ID          NAME                      DRIVER
5983103e59ed        wildflycouchbasejavaee7   overlay             
3d7a874aaffc        swarm-node-01/host        host                
a18b81496677        swarm-node-01/none        null                
553c100e40d0        swarm-node-02/bridge      bridge              
9f4e68fc868b        swarm-node-02/host        host                
e8d4f9608185        swarm-master/none         null                
7e5b82ff7a31        swarm-master/host         host                
411c7751b803        swarm-network             overlay             
b90942466c1e        swarm-node-01/bridge      bridge              
507d47fccb69        swarm-node-02/none        null                
d6511ffc4978        swarm-master/bridge       bridge  
```

The output message shows "None" driver where as its the "overlay" driver.
