### ISSUE TITLE
swarm label constaint is not working

### ISSUE THREAD

**Issue by marceloamaral** [docker/swarm#1830]
Hi I am using swarm with compose to deploy two container into two different host. Where the docker daemon on each host is configured with different label. I am also using consul.

I got the error ERROR: unable to find a node that satisfies x.storage==ssd

There exist a machine with this label, but swarm is not finding the machine. 

The docker compose yml file is:
```
app:
  image: flask/app
  links:
    - redis
  #environment:
   # - "constraint:x.pci==fpga"
app2:
  image: flask/app
  links:
    - redis
  environment:
    - "constraint:x.storage==ssd"
haproxy:
  image: tutum/haproxy
  links:
    - app
    - app2
  environment:
    - BACKEND_PORT=5000
nginx:
  image: nginx/loadbalancer
  ports:
    - "80:80"
  links:
    - haproxy
redis:
  image: redis
```

```
docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 8
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 host1: 172.20.0.16:2376
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 12.32 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, x.storage=ssd, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-17T19:49:07Z
 host2: 172.20.0.11:2376
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.45 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, x.pci=fpga, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-17T19:49:29Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.19.0-25-generic
Operating System: linux
Architecture: amd64
CPUs: 12
Total Memory: 28.77 GiB
Name: host2
```

```
docker version 
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   a0fd82b
 Built:        Thu Feb  4 08:55:18 UTC 2016
 OS/Arch:      linux/amd64
```
