### ISSUE TITLE
"docker-compose run" doesn't recognise an existing volume

### ISSUE THREAD

**Issue by gittycat** [docker/swarm#1955]
When running `docker-compose run <service> <cmd>` in a swarm context, the relationship between services and their mounted volumes as listed in `docker-compose.yml` doesn't seen to be respected.
(docker 1.10.2, swarm 1.1.0, compose 1.6.2, amazonec2, CLI from OSX)

I've better show an example to explain:

docker-compose.yml
```
version: '2'
services:
  bucket:
    image: alpine:3.3
    container_name: bucket
    volumes:
      - data:/data
    command: /bin/true
volumes:
  data:
```

Then we do
```
docker-compose up -d
echo "hello there" > foo.txt
docker cp foo.txt bucket:/data/
```
and look at the results using:
```
docker run --rm --volumes-from bucket alpine:3.3 ls -al /data
docker-compose run --rm bucket ls -al /data
```
Under a **non swarm** host, both of the last two commands return the same result (the listing of `foo.txt`).
In a swarm node, the first command returns `foo.txt` but not the second. Here's the output
```
+ docker run --rm --volumes-from bucket alpine:3.3 ls -al /data
total 12
drwxr-xr-x    2 root     root          4096 Mar 12 13:04 .
drwxr-xr-x   24 root     root          4096 Mar 12 13:04 ..
-rw-r--r--    1 root     root            12 Mar 12 13:04 foo.txt

+ docker-compose run --rm bucket ls -al /data
Creating volume "test_data" with default driver
total 8
drwxr-xr-x    2 root     root          4096 Mar 12 13:04 .
drwxr-xr-x   24 root     root          4096 Mar 12 13:04 ..
```
Note that `docker-compose` created a new volume "test_data" instead of using the one specified in the docker-compose.yml.

**Comment by gittycat** [comment]
I'm not sure if this is a docker-compose or swarm issue so I've also posted this on the docker compose issue tracking.

**Comment by echupriyanov** [comment]
Here is how to make your setup work with Swarm.
Here is list of my nodes:
```
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> docker info |grep node
 swarm-node-03a.cybertonica.aws: swarm-node-03a.cybertonica.aws:2376
 swarm-node-04a.cybertonica.aws: swarm-node-04a.cybertonica.aws:2376
 swarm-node-05a.cybertonica.aws: swarm-node-05a.cybertonica.aws:2376
 swarm-node-06a.cybertonica.aws: swarm-node-06a.cybertonica.aws:2376
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> 
```
Pick one node to hold your volume and create a named volume:
```
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> docker volume create --name=swarm-node-06a.cybertonica.aws/v3
v3
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2>  
```
Make sure there is only one volume with that name in cluster:
```
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> docker volume ls |grep v3
local               swarm-node-06a.cybertonica.aws/v3
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> 
```
Lets now add some data to that volume:
```
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> docker run -it --rm -e 'constraint:node==swarm-node-06a.cybertonica.aws' -v v3:/secrets alpine sh
/ # cd /secrets/
/secrets # date >testdata
/secrets # ⏎                                                                                                                                                                            eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> 
```
Now, `docker-compose.yml`:
```
version: '2'

services:
  app:
    image: alpine:3.3
    environment:
      - 'constraint:node==swarm-node-06a.cybertonica.aws'
    volumes:
      - vault:/secrets
    command: cat /secrets/testdata

volumes:
  vault:
    external:
      name: "v3"
```
And, finally:
```
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> docker-compose up 
Recreating t2_app_1
Attaching to t2_app_1
app_1 | Mon Mar 14 16:54:36 UTC 2016
t2_app_1 exited with code 0
eric@iMac-Eric /V/D/W/g/s/c/p/d/t2> 
```

The main point here is to describe exactly, where is your local volume is located.

The limitation for only unique volume name seems slightly artificial, and I think I know how to remove it.
