### ISSUE TITLE
Use same Consul for both overlay network and service discovery

### ISSUE THREAD

**Issue by fiunchinho** [docker/swarm#1968]
Hi!

I've got a swarm cluster running with an overlay network using Consul. Now, I'd like to run two services (`service1` and `service2`) that will talk to each other through service discovery with Consul. The problem is that, on startup, both services register themselves on Consul with a health check, but Consul can't ping the health URL since is not on the same network as those 2 services. Services register themselves with ip's like 10.x.x.x.

I can work around it by starting another container with Consul which is in the same network as `service1` and `service2`. That way, Consul can ping the health check URL and mark these services as healthy so they can talk to each other.
But this solution seems odd. Can't I just use the same Consul for both node discovery (Swarm) and service discovery (my App)?

I don't really want to run Consul in containers.

To set up the Docker Swarm cluster I more or less follow [these instructions](https://docs.docker.com/engine/userguide/networking/get-started-overlay/), that creates several nodes with docker machine and eventually creates an overlay network called `my-net`.

To work around the problem, I did it like

docker-compose.yml

```yaml
version: '2'

networks:
  default:
    external:
      name: my-net

services:
  service1:
    build: ./service1
    ports:
      - 8000

  service2:
    build: ./service2
    ports:
      - 8000
```

Starting the second Consul for service discovery in my application ( I did not added to the docker-compose file on purpose, since this will be shared between different applications using different docker-compose files):

```
bash
$ docker run --name=consul -d --net=my-net -p 8400:8400 -p 8500:8500 -p 8600:8600 progrium/consul -server -bootstrap -data-dir /data
```

Starting the application

```bash
$ docker-compose up
```
