### ISSUE TITLE
Question on how to perform zookeeper healthchecks in Swarm

### ISSUE THREAD

**Issue by ddewaele** [docker/swarm#2655]
We have a docker swarm cluster with 3 nodes. One of the components we deploy in swarm has native cluster capabilities and relies on zookeeper for cluster coordination and leader selection.

So we deployed zookeeper in the swarm with the config below (pinning each zookeeper instance to a specific node, and using the swarm overlay network service discovery to allow them to find each other).

This setup works fine. In our test environment (without swarm / high availability) we use zookeeper in standalone mode and can perforn a healthcheck easily

However, in a swarm cluster I can't get these healthchecks to work because all zookeepers run in replicated mode and need to be fully up and running before they are all able to resolve each other (zookeeper1 / zookeeper2 and zookeeper3 hostnames) through service discovery.

- Without the healthchecks, eventually all 3 instances are up and running , find each other, and agree on a leader.
- With the healtchecks in place, none of them reach that point, as each zookeeper is unable to find the other 2. (zookeeper1 can never resolve zookeeper2/3, zookeeper2 can never resolve zookeeper1/3, ....)

Are healthchecks possible in such a scenario and is this the correct way to deploy a zookeeper

```
version: '3'

services:
  zookeeper1:
    image: zookeeper
    user: root
    networks:
      - cnet
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
#    healthcheck:
#      test: ["CMD", "/bin/zkServer.sh","status"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == centos-a]
  zookeeper2:
    image: zookeeper
    user: root
    networks:
      - cnet
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=0.0.0.0:2888:3888  server.3=zookeeper3:2888:3888
#    healthcheck:
#      test: ["CMD", "/bin/zkServer.sh","status"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == centos-b]

  zookeeper3:
    image: zookeeper
    user: root
    networks:
      - cnet
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=0.0.0.0:2888:3888
#    healthcheck:
#      test: ["CMD", "/bin/zkServer.sh","status"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == centos-manager]
```
