### ISSUE TITLE
 v3 compose volumes not mounting via stack deploy

### ISSUE THREAD

**Issue by monowai** [docker/swarm#2663]
I was trying to mount a provisioned IOPS EBS on a machine acting as a Swarm master. I followed the instructions on this issue https://github.com/docker/docker/issues/30441 and used a definition such as:

```
version: "3"
services:
    postgres:
    image: postgres:9.5
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes
  postgres:
    driver_opts:
      o: bind
      type: none
      device: /data/database/postgres/bp
```

Works as expected when I run `docker-compose up -d` - postgress writes to the mounted volume.
Doesn't work when started via `docker stack deploy ...`  - the volume data is written to `/var/lib/docker/volumes/{net}-{volume}/_data` within the host.

I'm running `version 17.03.0-ce, build 60ccb22`. I'm guessing it's not yet supported? Cheers
