### ISSUE TITLE
swarm can not deploy service use compose file

### ISSUE THREAD

**Issue by justlooks** [docker/swarm#2681]
hi, i use the follow command to deploy service on my swarm cluster,it totally fine!
 docker service create --name registry --publish 5000:5000 registry:2

ID            NAME           MODE        REPLICAS  IMAGE
116fa01nxxh0  registry       replicated  1/1       registry:2

when i try use compose file to deploy ,the task seems failed

here is my compose file 
cat  docker-compose.yml

```
version: '3'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    networks:
      registry_net:
        ipv4_address: 172.16.20.13
    volumes:
      - /var/lib/docker/registry:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '1000'
          memory: 50M
        reservations:
          cpus: '1000'
          memory: 20M
      labels:
        registry: "this is the swarm service for local registry"

networks:
  registry_net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.16.20.0/24
```

and i use this to deploy service

docker stack deploy myregistry --compose-file ./docker-compose.yml
Ignoring unsupported options: restart

Creating network myregistry_registry_net
Creating service myregistry_registry 

# docker service ls
ID            NAME                 MODE        REPLICAS  IMAGE
s5dilsdv5ubu  myregistry_registry  replicated  0/1       registry:2

and i can not visit the port 5000

i do not know why?
