### ISSUE TITLE
problem in using compose file to deploy service

### ISSUE THREAD

**Issue by justlooks** [docker/swarm#2683]
this is ok
`docker service create --name registry --publish 5000:5000 --network my-net registry:2
`but when i write  compose file, i can not deploy service use " docker stack"

`docker stack deploy myregistry --compose-file ./docker-compose.yml`

here is my compose file

```
version: '3'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - outside
    volumes:
      - /var/lib/docker/registry:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '1000'
          memory: 50M
        reservations:
          cpus: '1000'
          memory: 20M
      labels:
        registry: "this is the swarm service for local registry"

networks:
  outside:
    external:
      name: my-net
```

```
# docker version && docker info
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
Containers: 16
 Running: 6
 Paused: 0
 Stopped: 10
Images: 30
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ogcg13p4jfywdvwp13kfhyqro
 Is Manager: true
 ClusterID: y4q20s848ebz5p9eqog3lm100
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.132.41.234
 Manager Addresses:
  10.132.41.234:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.389 GiB
Name: test_centos7.2
ID: JEZA:Q3OT:4XO5:RMCI:RZOJ:T5RQ:M465:H3XP:WTZI:VNZR:X3FM:PT5B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: 15925631072
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 10.132.41.234:5000
 127.0.0.0/8
Live Restore Enabled: false
```
