### ISSUE TITLE
Binding to ip in swarm

### ISSUE THREAD

**Issue by ruudboon** [docker/swarm#2804]
I got host system with 2 ip's. I would like to setup a swarm and have different containers open port 80 on different ip's. 
When using the config below I get:

failed to create service staging_test: Error response from daemon: rpc error: code = InvalidArgument desc = port '80' is already in use by service 'staging_test1' (????) as an ingress port

Looks like the swarm isn't binding to the IP
```
version: '3'

services:
  test1:
    image: frameloss/empty-container
    ports:
        - "1.2.3.4:80:80"
  test:
    image: frameloss/empty-container
    ports:
        - "4.3.2.1:80:80"
```
