### ISSUE TITLE
global mode,link service per node

### ISSUE THREAD

**Issue by foxundermoon** [docker/swarm#2808]
i am use global mode to deploy my service.
 the `backend-service` is backed rest service,
the `ui` is frontend web  manager for per  service.
how to link the `ui` to `backend`

```yml
version: '3.3'
services:
  backend-service:
    image: 'backend'
    ports:
      - target: 6800
        published: 6800
        protocol: tcp
        mode: host
    deploy:
      mode: global
  ui:
    image: 'ui'
    ports:
      - target: 6801
        published: 6801
        protocol: tcp
        mode: host 
    environment:
      - 'SERVER=http://backend-service:6800'
      - HOST=0.0.0.0
    deploy:
      mode: global
```
