### ISSUE TITLE
Docker: Unable to ping another host from inside of container running in swarm

### ISSUE THREAD

**Issue by yogeshkathayat** [docker/swarm#2966]
Environment:-

- Ubuntu 18.04
- Docker version 18.09.7, build 2d0083d
- image yogeshkathayat/node-ping which is a simple nodejs app running on a node-alpine build
- my current host IP: 10.255.8.21
- Ip that I want to ping: 10.255.8.53

My compose file:-
```
version: "3.3"
networks:
  basic:
services:
  ping-test:
    image: yogeshkathayat/node-ping
    deploy:
      replicas: 1
    networks:
      - basic
    ports:
      - "3000:3000"
```

Issue:-
I am not able to ping another host in the same local network from inside of the container,
if I remove `ports` section from my Compose file then it is working perfectly. but I want to expose the port to the outside world.

Steps:-

1. docker swarm init
2. docker stack deploy --compose-file docker-compose.yml ping
3. docker exec -it <containerid> /bin/bash  //go inside the container
4. ping host in the same subnet or network

**Comment by information-security** [comment]
Please use this format for your ports and see if it solves your problem:

```
ports:
  - target: 3000
    published: 3000
    protocol: tcp
    mode: host
```
